modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="food_within"
version="1.0.0"
displayName="Food Within"
credits="Created Using MCreator"
displayURL="https://mcreator.net"
authors="Kade"
description='''
A mod that adds food within different types of mobs. Most if not all mobs will have a one to many different food drops.
'''

[[dependencies.food_within]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.food_within]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.food_within]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

